repos:
-   repo: local
    hooks:
    -   id: hw
        name: homework
        entry: python3 --version
        #entry: python3 ./src/gate.py -f ./data/auto93.csv -t all
        language: system
        always_run: true
        pass_filenames: false

